name: Generate GitHub Profile Summary Cards

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main, master ]
    paths: [ 'README.md' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Generate GitHub Profile Summary Cards
        run: |
          npm install
          npm run generate:gh-profile -- --username ${{ github.repository_owner }} --theme tokyonight

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Generate profile summary cards'
          git push
